site_name: Documentation
site_url: https://docs.docketanalyzer.com

theme:
  title: Material
  name: material
  palette:
    scheme: slate
    primary: black
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Nunito
  features:
    - navigation.instant

extra:
  homepage: https://docketanalyzer.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          allow_inspection: true
