name: Tests

on:
  workflow_call:

jobs:      
  tests:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
      RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
      RUNPOD_OCR_ENDPOINT_ID: ${{ secrets.RUNPOD_OCR_ENDPOINT_ID }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      COURTLISTENER_TOKEN: ${{ secrets.COURTLISTENER_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set Up
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install '.[all,dev]'
      
      - name: Test with pytest
        run: |
          pytest -m 'not (cost or local)'
